package com.b2la.antiplagiat.integration;

import com.b2la.antiplagiat.entites.AnalysisHistory;
import com.b2la.antiplagiat.entites.Document;
import com.b2la.antiplagiat.entites.Roles;
import com.b2la.antiplagiat.entites.Status;
import com.b2la.antiplagiat.entites.Users;
import com.b2la.antiplagiat.enumerote.Role;
import com.b2la.antiplagiat.enumerote.StatusEnum;
import com.b2la.antiplagiat.repository.AnalysisHistoryRepository;
import com.b2la.antiplagiat.repository.DocumentsRespository;
import com.b2la.antiplagiat.repository.ReportRepository;
import com.b2la.antiplagiat.repository.RolesRepository;
import com.b2la.antiplagiat.repository.StatusRepository;
import com.b2la.antiplagiat.repository.UsersRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;

@SpringBootTest
@AutoConfigureMockMvc
public class ReportIntegrationTest {

    @Autowired
    MockMvc mockMvc;

    @Autowired
    UsersRepository usersRepository;

    @Autowired
    RolesRepository rolesRepository;

    @Autowired
    DocumentsRespository documentsRespository;

    @Autowired
    AnalysisHistoryRepository historyRepository;

    @Autowired
    ReportRepository reportRepository;

    @Autowired
    StatusRepository statusRepository;

    final ObjectMapper mapper = new ObjectMapper();

    Roles adminRole;
    Roles studentRole;
    Users owner;
    Users other;

    @BeforeEach
    public void setup() throws Exception {
        reportRepository.deleteAll();
        historyRepository.deleteAll();
        documentsRespository.deleteAll();
        usersRepository.deleteAll();
        rolesRepository.deleteAll();
        statusRepository.deleteAll();

        adminRole = rolesRepository.save(Roles.builder().libelle(Role.ADMIN).build());
        studentRole = rolesRepository.save(Roles.builder().libelle(Role.STUDENT).build());

        owner = usersRepository.save(Users.builder()
                .username("owner")
                .email("owner@example.com")
                .password("pass")
                .phoneNumber("000")
                .role(studentRole)
                .build());

        other = usersRepository.save(Users.builder()
                .username("other")
                .email("other@example.com")
                .password("pass")
                .phoneNumber("111")
                .role(studentRole)
                .build());

        // create a small text file to represent stored document
        Path tmp = Files.createTempFile("doc-", ".txt");
        Files.writeString(tmp, "This is a test document. Generated by AI? chatgpt mention.");

        Document d = Document.builder()
                .name("testdoc")
                .faculty("f")
                .department("d")
                .author("a")
                .yearOfAcademic("2026")
                .matriculation(UUID.randomUUID().toString())
                .urlFile(tmp.toAbsolutePath().toString())
                .storedFileName(tmp.toAbsolutePath().toString())
                .originalFileName(tmp.getFileName().toString())
                .contentType("text/plain")
                .fileSize(Files.size(tmp))
                .user(owner)
                .build();

        documentsRespository.save(d);
    }

    @Test
    public void ownerCanGenerateReport() throws Exception {
        var doc = documentsRespository.findAll().get(0);
        String id = createCompletedAnalysis(doc, owner).getId().toString();

        // generate report
        String reportBody = mapper.writeValueAsString(java.util.Map.of("analysisId", id));
        mockMvc.perform(post("/api/reports")
                .with(user(owner.getUsername()).roles("STUDENT"))
                .contentType(MediaType.APPLICATION_JSON)
                .content(reportBody))
                .andExpect(status().isCreated());
    }

    @Test
    public void otherCannotGenerateReport() throws Exception {
        var doc = documentsRespository.findAll().get(0);
        String id = createCompletedAnalysis(doc, owner).getId().toString();

        String reportBody = mapper.writeValueAsString(java.util.Map.of("analysisId", id));
        mockMvc.perform(post("/api/reports")
                .with(user(other.getUsername()).roles("STUDENT"))
                .contentType(MediaType.APPLICATION_JSON)
                .content(reportBody))
                .andExpect(status().isForbidden());
    }

    @Test
    public void adminCanAccessAnyReport() throws Exception {
        var doc = documentsRespository.findAll().get(0);
        String id = createCompletedAnalysis(doc, owner).getId().toString();

        String reportBody = mapper.writeValueAsString(java.util.Map.of("analysisId", id));
        // admin can generate
        mockMvc.perform(post("/api/reports")
                .with(user("admin").roles("ADMIN"))
                .contentType(MediaType.APPLICATION_JSON)
                .content(reportBody))
                .andExpect(status().isCreated());

        // admin can list and get
        mockMvc.perform(get("/api/reports")
                .with(user("admin").roles("ADMIN")))
                .andExpect(status().isOk());
    }

    @Test
    public void reportRequiresExactlyOneIdentifier() throws Exception {
        var doc = documentsRespository.findAll().get(0);
        String id = createCompletedAnalysis(doc, owner).getId().toString();

        mockMvc.perform(post("/api/reports")
                .with(user(owner.getUsername()).roles("STUDENT"))
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
                .andExpect(status().isBadRequest());

        String reportBody = mapper.writeValueAsString(java.util.Map.of(
                "analysisId", id,
                "documentId", doc.getId().toString()
        ));
        mockMvc.perform(post("/api/reports")
                .with(user(owner.getUsername()).roles("STUDENT"))
                .contentType(MediaType.APPLICATION_JSON)
                .content(reportBody))
                .andExpect(status().isBadRequest());
    }

    @Test
    public void failedAnalysisCannotGenerateReport() throws Exception {
        var doc = documentsRespository.findAll().get(0);
        String id = createAnalysis(doc, owner, StatusEnum.FAILED).getId().toString();

        String reportBody = mapper.writeValueAsString(java.util.Map.of("analysisId", id));
        mockMvc.perform(post("/api/reports")
                .with(user(owner.getUsername()).roles("STUDENT"))
                .contentType(MediaType.APPLICATION_JSON)
                .content(reportBody))
                .andExpect(status().isConflict());
    }

    private AnalysisHistory createCompletedAnalysis(Document document, Users user) {
        return createAnalysis(document, user, StatusEnum.COMPLETED);
    }

    private AnalysisHistory createAnalysis(Document document, Users user, StatusEnum statusEnum) {
        Status completed = statusRepository.save(Status.builder().libelle(statusEnum).build());
        return historyRepository.save(AnalysisHistory.builder()
                .document(document)
                .user(user)
                .overallScore(12.5)
                .aiScore(0.0)
                .status(completed)
                .details("{\"status\":\"" + statusEnum.name() + "\"}")
                .build());
    }
}
