spring.application.name=antiplagiat

spring.datasource.url=jdbc:mariadb://localhost:3306/antiplagiat
#spring.datasource.username=b2la
#spring.datasource.password=Samba@@@2026
spring.datasource.username=dbr
spring.datasource.password=Samba@@@2026
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.naming.physique-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.testWhileIdle=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.validationQuery=SELECT 1

